INSERT INTO `sys_menu` (`id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`) VALUES
 ('1', '0', '系统管理', NULL, NULL, '0', 'fa fa-cog', '0'),
 ('2', '1', '管理员管理', 'modules/sys/user.html', NULL, '1', 'fa fa-user', '1'),
 ('3', '1', '角色管理', 'modules/sys/role.html', NULL, '1', 'fa fa-user-secret', '2'),
 ('4', '1', '菜单管理', 'modules/sys/menu.html', NULL, '1', 'fa fa-th-list', '3'),
 ('5', '1', 'SQL监控', 'druid/sql.html', NULL, '1', 'fa fa-bug', '4'),
 ('15', '2', '查看', NULL, 'sys:user:list,sys:user:info', '2', NULL, '0'),
 ('16', '2', '新增', NULL, 'sys:user:save,sys:role:select', '2', NULL, '0'),
 ('17', '2', '修改', NULL, 'sys:user:update,sys:role:select', '2', NULL, '0'),
 ('18', '2', '删除', NULL, 'sys:user:delete', '2', NULL, '0'),
 ('19', '3', '查看', NULL, 'sys:role:list,sys:role:info', '2', NULL, '0'),
 ('20', '3', '新增', NULL, 'sys:role:save,sys:menu:perms', '2', NULL, '0'),
 ('21', '3', '修改', NULL, 'sys:role:update,sys:menu:perms', '2', NULL, '0'),
 ('22', '3', '删除', NULL, 'sys:role:delete', '2', NULL, '0'),
 ('23', '4', '查看', NULL, 'sys:menu:list,sys:menu:info', '2', NULL, '0'),
 ('24', '4', '新增', NULL, 'sys:menu:save,sys:menu:select', '2', NULL, '0'),
 ('25', '4', '修改', NULL, 'sys:menu:update,sys:menu:select', '2', NULL, '0'),
 ('26', '4', '删除', NULL, 'sys:menu:delete', '2', NULL, '0'),
 ('27', '1', '参数管理', 'modules/sys/config.html', 'sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete', '1', 'fa fa-sun-o', '6'),
 ('29', '1', '系统日志', 'modules/sys/log.html', 'sys:log:list', '1', 'fa fa-file-text-o', '7'),
 ('31', '1', '部门管理', 'modules/sys/dept.html', NULL, '1', 'fa fa-file-code-o', '1'),
 ('32', '31', '查看', NULL, 'sys:dept:list,sys:dept:info', '2', NULL, '0'),
 ('33', '31', '新增', NULL, 'sys:dept:save,sys:dept:select', '2', NULL, '0'),
 ('34', '31', '修改', NULL, 'sys:dept:update,sys:dept:select', '2', NULL, '0'),
 ('35', '31', '删除', NULL, 'sys:dept:delete', '2', NULL, '0'),
 (36, 1, '字典管理', 'modules/sys/dict.html', NULL, 1, 'fa fa-bookmark-o', 6),
 (37, 36, '查看', NULL, 'sys:dict:list,sys:dict:info', 2, NULL, 6),
 (38, 36, '新增', NULL, 'sys:dict:save', 2, NULL, 6),
 (39, 36, '修改', NULL, 'sys:dict:update', 2, NULL, 6);
